#!/bin/sh

# dbus-monitor is run as a child process to this script. Kill child process too when the script terminates.
trap 'pkill -9 -P $$ && exit 0' INT TERM

interface=org.freedesktop.ModemManager1.Call
member=StateChanged

dbus-monitor --system "type='signal',interface='$interface',member='$member'" |
        while read -r line; do
                state=$(echo "$line" | awk '/\<int32\>/ {print $2}')
                if [ -n "$state" ]; then
                        # Call State is based on https://www.freedesktop.org/software/ModemManager/doc/latest/ModemManager/ModemManager-Flags-and-Enumerations.html#MMCallState
                        if [ "$state" -eq '0' ] || [ "$state" -eq '3' ]; then
                                echo "Call Started"

                                pactl set-sink-volume @DEFAULT_SINK@ 15%
                                sleep 0.2
                                pw-loopback -m '[FL FR]' --capture-props='media.class=Audio/Sink' &
                                pw-loopback -m '[FL FR]' --playback-props='media.class=Audio/Source' &
                        fi

                        if [ "$state" -eq '7' ]; then
                                echo "Call Ended"
                                killall -9 pw-loopback &
                                sleep 2
                                pactl set-default-sink alsa_output.platform-sound.HiFi__Speaker__sink
                                pactl set-sink-volume @DEFAULT_SINK@ 90%

                        fi
                fi
        done &

wait
